image: archlinux
packages:
  - tfenv
secrets:
  - cb219abd-c794-42c6-af48-0edc2f8dd5df
  - 3b922da4-d093-4870-85eb-393a4c83dd78
environment:
  project: dns
tasks:
  - set-envs: |
      echo "shh, setting some secrets!"
      set +x
      bash ${project}/ci/build-tfc-rc.sh
      bash ${project}/ci/build-tfvars-file.sh
      set -x
      echo "ok, back to work."
  - install-tfenv: |
      pushd "${project}"
      sudo tfenv install
      sudo tfenv use
      popd
  - terraform-init: |
      pushd "${project}"
      terraform init -input=false
      popd
  - terraform-plan: |
      pushd "${project}"
      terraform -auto-approve
      popd
