image: archlinux
packages:
  - tfenv
secrets:
  - ea59ef6c-8791-4e72-868c-6f73d1d97f47
  - 2ccc82ee-d6e7-4764-92be-6202108272a0
environment:
  project: dns
  TFENV_INSTALL_DIR: ~/.tfenv/
  TF_VAR_gandi_api_key: $(cat ~/.gandi-api-key)
  TF_LOG: trace
tasks:
    pre-setup: |
      pushd "${project}"
      bash -c ./ci/build-tfc-rc.sh
      popd
  - setup: |
      pushd "${project}"
      sudo tfenv install
      popd
  - init: |
      pushd "${project}"
      terraform init -input=false
      popd
  - plan: |
      echo "now let's do the plan!"