image: archlinux
packages:
  - tfenv
secrets:
  - b4c86ba6-f6a1-4308-833d-0ef4c2d8dbf6
environment:
  project: dns
  TFENV_INSTALL_DIR: ~/.tfenv/
tasks:
  - setup: |
      echo "TF_TOKEN_app_terraform_io=$(cat ~/.org-key-tf-gandi-dns)" >> ~/.buildenv
      pushd "${project}"
      sudo tfenv install
      popd
  - init: |
      pushd "${project}"
      terraform init
      popd
  - plan: |
      echo "now let's do the plan!"