image: archlinux
packages:
  - tfenv
secrets:
  - ea59ef6c-8791-4e72-868c-6f73d1d97f47
  - 2ccc82ee-d6e7-4764-92be-6202108272a0
environment:
  project: dns
  TFENV_INSTALL_DIR: ~/.tfenv/
  TF_VAR_gandi_api_key: ""
  TF_TOKEN_app_terraform_io: ""
tasks:
  - pre-setup: |
      pushd "${project}"
      bash ./ci/build-tfc-rc.sh
      popd
  - setup: |
  - set-envs: |
      TF_VAR_gandi_api_key=$(cat ~/.gandi-api-key)
      TF_TOKEN_app_terraform_io=$(cat ~/.user-token-tf-gandi-dns)
      pushd "${project}"
      sudo tfenv install
      popd
  - init: |
      pushd "${project}"
      terraform init -input=false
      popd
  - plan: |
      pushd "${project}"
      terraform plan
      popd