image: archlinux
packages:
  - tfenv
secrets:
  - cb219abd-c794-42c6-af48-0edc2f8dd5df
  - 3b922da4-d093-4870-85eb-393a4c83dd78
environment:
  project: dns
  TFENV_INSTALL_DIR: ~/.tfenv/
  TF_VAR_gandi_api_key: ""
  TF_TOKEN_app_terraform_io: ""
tasks:
  - set-envs: |
      set +x
      TF_VAR_gandi_api_key="$(cat ~/.gandi-api-key)"
      TF_TOKEN_app_terraform_io="$(cat ~/.user-token-tf-gandi-dns)"
      set -x
  - install-tfenv: |
      pushd "${project}"
      sudo tfenv install
      popd
  - terraform-init: |
      pushd "${project}"
      terraform init -input=false
      popd
  - terraform-plan: |
      pushd "${project}"
      terraform plan
      popd